### ISSUE TITLE
0.2.1 version don't compile

### ISSUE THREAD

**Issue by Limonlol** [icerockdev/moko-units#9]
`e: Compilation failed: Could not find serialized descriptor for index: -2639035847497420885 dev.icerock.moko.units,UnitCollectionViewDataSource,<init>`
cannot compile 0.2.1 version with top error. 0.2.0-dev-4 release work.

**Comment by Alex009** [comment]
error was in project configuration. other dependencies (moko-widgets) was old version wich use old release
